/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompanyNews: typeof import('./src/components/CompanyNews.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    TaskForm: typeof import('./src/components/TaskForm.vue')['default']
    TaskItem: typeof import('./src/components/TaskItem.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
  }
}
